#!/usr/bin/env python3
"""
Security Report Generator
Generates markdown security reports from scan and intel data.
"""

import json
from datetime import datetime
from typing import Dict, List

class SecurityReport:
    def __init__(self):
        self.template = """# 🔒 OpenClaw Security Report
Generated: {timestamp}

## Executive Summary
- **Total Issues Found:** {total_issues}
- **High Severity:** 🔴 {high}
- **Medium Severity:** 🟡 {medium}
- **Low Severity:** 🟢 {low}

## Severity Breakdown

### Critical Findings ({high})
{high_findings}

### Medium Severity Issues ({medium})
{medium_findings}

### Low Severity Notes ({low})
{low_findings}

## Affected Components
{components}

## Remediation Steps
{remediation_steps}

## Intelligence Sources
{sources}

---
*Report generated by OpenClaw Security Scanner*
"""
    
    def generate(self, scan_results: Dict, intel_results: Dict = None) -> str:
        """Generate markdown report."""
        summary = scan_results.get('summary', {'High': 0, 'Medium': 0, 'Low': 0})
        issues = scan_results.get('issues', [])
        
        # Group issues by severity
        high_issues = [i for i in issues if i['severity'] == 'High']
        medium_issues = [i for i in issues if i['severity'] == 'Medium']
        low_issues = [i for i in issues if i['severity'] == 'Low']
        
        # Format findings
        def format_finding(issue, idx):
            return f"{idx}. **{issue['type']}**\n   - Location: {issue.get('file', issue.get('port', 'N/A'))}\n   - Issue: {issue['issue']}\n   - Fix: {issue['remediation']}"
        
        high_findings = '\n'.join(format_finding(i, idx) for idx, i in enumerate(high_issues, 1)) or "No high severity issues found."
        medium_findings = '\n'.join(format_finding(i, idx) for idx, i in enumerate(medium_issues, 1)) or "No medium severity issues found."
        low_findings = '\n'.join(format_finding(i, idx) for idx, i in enumerate(low_issues, 1)) or "No low severity issues found."
        
        # Get unique components
        components = set()
        remediation_steps = set()
        for issue in issues:
            components.add(issue.get('type', 'Unknown'))
            remediation_steps.add(issue.get('remediation', ''))
        
        # Format sources
        sources = "No external intelligence gathered."
        if intel_results:
            sources_list = []
            for source, findings in intel_results.get('sources', {}).items():
                for finding in findings:
                    sources_list.append(f"- [{source}]({finding['url']}): {finding['post'][:100]}...")
            sources = '\n'.join(sources_list) if sources_list else sources
        
        report = self.template.format(
            timestamp=datetime.now().isoformat(),
            total_issues=len(issues),
            high=summary.get('High', 0),
            medium=summary.get('Medium', 0),
            low=summary.get('Low', 0),
            high_findings=high_findings,
            medium_findings=medium_findings,
            low_findings=low_findings,
            components='\n'.join(f"- {c}" for c in components),
            remediation_steps='\n'.join(f"- {r}" for r in remediation_steps if r),
            sources=sources
        )
        
        return report
    
    def save(self, content: str, filepath: str = "/tmp/openclaw-security-scanner/report.md"):
        """Save report to file."""
        with open(filepath, 'w') as f:
            f.write(content)
        print(f"📄 Report saved to {filepath}")
        return filepath

if __name__ == '__main__':
    # Demo with sample data
    sample_scan = {
        'summary': {'High': 2, 'Medium': 3, 'Low': 4},
        'issues': [
            {
                'type': 'credential_exposure',
                'severity': 'High',
                'file': '~/.clawdbot/config.json',
                'issue': 'API key found in plain text',
                'remediation': 'Use environment variables'
            },
            {
                'type': 'injection_pattern',
                'severity': 'High',
                'file': '~/.clawdbot/skills/test.md',
                'issue': 'Command substitution detected',
                'remediation': 'Sanitize input'
            }
        ]
    }
    
    sample_intel = {
        'sources': {
            'X': [{'url': 'https://x.com/user/1', 'post': 'Found an issue...', 'source': 'X'}],
            'Reddit': [{'url': 'https://reddit.com/r/2', 'post': 'Discussion...', 'source': 'Reddit'}]
        }
    }
    
    report = SecurityReport()
    content = report.generate(sample_scan, sample_intel)
    report.save(content)
    
    print("\n" + "="*60)
    print(content[:1000] + "..." if len(content) > 1000 else content)
